# Diabetes Prediction with ML

## The main objective of the project is to predict if patient is having diabetes or not

In [1]:
# Steps Followed:
# -> We have used Pima Dataset giving by our professor
# -> Loaded data into jupyter notebook using pandas
# -> Performed data cleaning, split the data into train and test, trained the model, evaluated and imporved the performance of the model

In [2]:
# Models used: Naive Bayes, Random Forest, K-nearest neighbors
# conclusion: we have decided Random Forest as the best model since its accuracy:, precision:, recall:, F1 score:,

In [3]:
# importing dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [4]:
#Data-Loading
df = pd.read_excel('pima-data.xlsx')
df

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,diabetes_orig,skin,has_diabetes,diabetes
0,6,148,72,35,0,33.6,0.627,50,1,1.3790,True,True
1,1,85,66,29,0,26.6,0.351,31,0,1.1426,False,False
2,8,183,64,0,0,23.3,0.672,32,1,0.0000,True,True
3,1,89,66,23,94,28.1,0.167,21,0,0.9062,False,False
4,0,137,40,35,168,43.1,2.288,33,1,1.3790,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,1.8912,False,False
764,2,122,70,27,0,36.8,0.340,27,0,1.0638,False,False
765,5,121,72,23,112,26.2,0.245,30,0,0.9062,False,False
766,1,126,60,0,0,30.1,0.349,47,1,0.0000,True,True


# Data Cleaning Steps:
## -> Treating null values
## -> Remove duplicate rows & columns
## -> Finding co-realted columns
## -> Converting categorical data to numeric data
## -> Replacing zeros in the input columns
## -> Standardizing the data
## -> Removing low impactfull columns
## -> Balancing the data

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   num_preg       768 non-null    int64  
 1   glucose_conc   768 non-null    int64  
 2   diastolic_bp   768 non-null    int64  
 3   thickness      768 non-null    int64  
 4   insulin        768 non-null    int64  
 5   bmi            768 non-null    float64
 6   diab_pred      768 non-null    float64
 7   age            768 non-null    int64  
 8   diabetes_orig  768 non-null    int64  
 9   skin           768 non-null    float64
 10  has_diabetes   768 non-null    bool   
 11  diabetes       768 non-null    bool   
dtypes: bool(2), float64(3), int64(7)
memory usage: 61.6 KB


In [6]:
# stp1: check if dataset contains null values
df.isnull().sum()

num_preg         0
glucose_conc     0
diastolic_bp     0
thickness        0
insulin          0
bmi              0
diab_pred        0
age              0
diabetes_orig    0
skin             0
has_diabetes     0
diabetes         0
dtype: int64

In [7]:
# Remove duplicate rows & columns

In [8]:
# checking duplicate rows
df[df.duplicated()]

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,diabetes_orig,skin,has_diabetes,diabetes


In [9]:
# checking duplicate columns
df.T.duplicated()

num_preg         False
glucose_conc     False
diastolic_bp     False
thickness        False
insulin          False
bmi              False
diab_pred        False
age              False
diabetes_orig    False
skin             False
has_diabetes      True
diabetes          True
dtype: bool

In [10]:
# Out of duplicate columns has_diabetes & diabetes dropping any column
df.drop(['diabetes','has_diabetes'], axis = 1, inplace = True)

In [11]:
df.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,diabetes_orig,skin
0,6,148,72,35,0,33.6,0.627,50,1,1.3790
1,1,85,66,29,0,26.6,0.351,31,0,1.1426
2,8,183,64,0,0,23.3,0.672,32,1,0.0000
3,1,89,66,23,94,28.1,0.167,21,0,0.9062
4,0,137,40,35,168,43.1,2.288,33,1,1.3790


## Droping co-related columns

In [12]:
df.corr()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,diabetes_orig,skin
num_preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898,-0.081672
glucose_conc,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581,0.057328
diastolic_bp,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068,0.207371
thickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752,1.000000
insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548,0.436783
bmi,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695,0.392573
diab_pred,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844,0.183928
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356,-0.113970
diabetes_orig,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000,0.074752
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752,1.000000


In [13]:
df.corr().style.background_gradient(cmap='coolwarm')

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,diabetes_orig,skin
num_preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898,-0.081672
glucose_conc,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581,0.057328
diastolic_bp,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068,0.207371
thickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752,1.000000
insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548,0.436783
bmi,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695,0.392573
diab_pred,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844,0.183928
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356,-0.113970
diabetes_orig,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000,0.074752
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752,1.000000


In [14]:
#co-related columns 
# 1. skin & thickness

In [15]:
#checking if skin and thickness are duplicate columns
difference = df['skin']- df['thickness']
difference

0     -33.6210
1     -27.8574
2       0.0000
3     -22.0938
4     -33.6210
        ...   
763   -46.1088
764   -25.9362
765   -22.0938
766     0.0000
767   -29.7786
Length: 768, dtype: float64

In [16]:
# Skin & thickness not duplicate columns
# To decide which col to drop checking its corelation with output column
cor_col = df[['skin', 'thickness', 'diabetes_orig']]
cor_col.corr().style.background_gradient(cmap='coolwarm')

,skin,thickness,diabetes_orig
skin,1.000000,1.000000,0.074752
thickness,1.000000,1.000000,0.074752
diabetes_orig,0.074752,0.074752,1.000000


In [17]:
# the absolute value of both against diabetes_orig is same so drop any column
df.drop('skin', axis = 1, inplace = True)

In [18]:
df.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,diabetes_orig
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


# Convert categorical data to numeric

In [19]:
df.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,diabetes_orig
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


## No categorical data present

# Data Balancing

In [20]:
# Checking How many true's & false's present in the data
num_true = len(df.loc[df['diabetes_orig'] == 1])
num_false = len(df.loc[df['diabetes_orig'] == 0])
print(num_true)
print(num_false)

268
500


In [21]:
true_percentage = (( num_true / (num_true+num_false) ) *100)
false_percentage = (( num_false / (num_true+num_false) ) *100)

print(true_percentage)

print(false_percentage)

34.89583333333333
65.10416666666666


# Train Test Split

In [22]:
df.columns

Index(['num_preg', 'glucose_conc', 'diastolic_bp', 'thickness', 'insulin',
       'bmi', 'diab_pred', 'age', 'diabetes_orig'],
      dtype='str')

In [23]:
# Splitting the input columns and prediction columns
input_column = [ 'num_preg', 'glucose_conc', 'diastolic_bp', 'thickness', 'insulin',
       'bmi', 'diab_pred', 'age' ]
output_column = [ 'diabetes_orig' ]

x = df[input_column].values
y = df[[ 'diabetes_orig' ]].values

# print(x)


In [24]:
# print(y)

In [25]:
# Split data into train and test set
x_train,x_test, y_train,y_test = train_test_split (x,y,test_size=0.3 , random_state=42 )

# print(x_train)
# print(x_test)
# print(y_train)
# print(y_test)


In [26]:
print(x_train.shape)

(537, 8)


In [27]:
print(x_test.shape)

(231, 8)


In [28]:
print(y_train.shape)

(537, 1)


In [29]:
print(y_test.shape)

(231, 1)


## Checking class balance in the train data

In [30]:
len(x_train)

537

In [31]:
len(df)

768

In [32]:
print("{0:0.2f}% in training set".format((len(x_train)/len(df.index))*100))

69.92% in training set


In [33]:
print("{0:0.2f}% in testing set".format((len(x_test)/len(df.index))*100))

30.08% in testing set


In [34]:
print("training true : {0} ({1:0.2f}%)".format( len(y_train[y_train[ : ] == 1]),
                                                ( len(y_train[y_train[ : ] == 1]) / len(y_train)*100 )) )

print("training false : {0} ({1:0.2f}%)".format( len(y_train[y_train[ : ] == 0]),
                                                ( len(y_train[y_train[ : ] == 0]) / len(y_train)*100 )) )

print("Test true : {0} ({1:0.2f}%)".format( len(y_test[y_test[ : ] == 1]),
                                                ( len(y_test[y_test[ : ] == 1]) / len(y_test)*100 )) )

print("Test false : {0} ({1:0.2f}%)".format( len(y_test[y_test[ : ] == 0]),
                                                ( len(y_test[y_test[ : ] == 0]) / len(y_test)*100 ) ) )


training true : 188 (35.01%)
training false : 349 (64.99%)
Test true : 80 (34.63%)
Test false : 151 (65.37%)


In [35]:
x_train[:5]

array([[1.00e+00, 9.50e+01, 6.00e+01, 1.80e+01, 5.80e+01, 2.39e+01,
        2.60e-01, 2.20e+01],
       [5.00e+00, 1.05e+02, 7.20e+01, 2.90e+01, 3.25e+02, 3.69e+01,
        1.59e-01, 2.80e+01],
       [0.00e+00, 1.35e+02, 6.80e+01, 4.20e+01, 2.50e+02, 4.23e+01,
        3.65e-01, 2.40e+01],
       [4.00e+00, 1.31e+02, 6.80e+01, 2.10e+01, 1.66e+02, 3.31e+01,
        1.60e-01, 2.80e+01],
       [1.00e+00, 1.03e+02, 3.00e+01, 3.80e+01, 8.30e+01, 4.33e+01,
        1.83e-01, 3.30e+01]])

## Post Split Preparation

## Check if any zero values present or not

In [36]:
df.columns

Index(['num_preg', 'glucose_conc', 'diastolic_bp', 'thickness', 'insulin',
       'bmi', 'diab_pred', 'age', 'diabetes_orig'],
      dtype='str')

In [37]:
total_num_preg = len(df.loc[df['num_preg'] == 0])
print(f"num of rows missing in num_preg col is {total_num_preg}")

total_glucose_conc = len(df.loc[df['glucose_conc'] == 0])
print(f"num of rows missing in glucose_conc col is {total_glucose_conc}")

total_diastolic_bp = len(df.loc[df['diastolic_bp'] == 0])
print(f"num of rows missing in diastolic_bp col is {total_diastolic_bp}")

total_thickness = len(df.loc[df['thickness'] == 0])
print(f"num of rows missing in thickness col is {total_thickness}")

total_insulin = len(df.loc[df['insulin'] == 0])
print(f"num of rows missing in insulin col is {total_insulin}")

total_bmi = len(df.loc[df['bmi'] == 0])
print(f"num of rows missing in bmi col is {total_bmi}")

total_diab_pred = len(df.loc[df['diab_pred'] == 0])
print(f"num of rows missing in diab_pred col is {total_diab_pred}")

total_age = len(df.loc[df['age'] == 0])
print(f"num of rows missing in age col is {total_age}")


num of rows missing in num_preg col is 111
num of rows missing in glucose_conc col is 5
num of rows missing in diastolic_bp col is 35
num of rows missing in thickness col is 227
num of rows missing in insulin col is 374
num of rows missing in bmi col is 11
num of rows missing in diab_pred col is 0
num of rows missing in age col is 0


In [38]:
fill_zero = SimpleImputer (missing_values=0,strategy='mean')
x_train = fill_zero.fit_transform(x_train)
x_test = fill_zero.fit_transform(x_test)
x_train[:5]

array([[1.00000000e+00, 9.50000000e+01, 6.00000000e+01, 1.80000000e+01,
        5.80000000e+01, 2.39000000e+01, 2.60000000e-01, 2.20000000e+01],
       [5.00000000e+00, 1.05000000e+02, 7.20000000e+01, 2.90000000e+01,
        3.25000000e+02, 3.69000000e+01, 1.59000000e-01, 2.80000000e+01],
       [4.34056399e+00, 1.35000000e+02, 6.80000000e+01, 4.20000000e+01,
        2.50000000e+02, 4.23000000e+01, 3.65000000e-01, 2.40000000e+01],
       [4.00000000e+00, 1.31000000e+02, 6.80000000e+01, 2.10000000e+01,
        1.66000000e+02, 3.31000000e+01, 1.60000000e-01, 2.80000000e+01],
       [1.00000000e+00, 1.03000000e+02, 3.00000000e+01, 3.80000000e+01,
        8.30000000e+01, 4.33000000e+01, 1.83000000e-01, 3.30000000e+01]])

In [39]:
(x_train == 0).sum()

np.int64(0)

# Standardizing

In [40]:
# It is a data processing technique which is used to make all values into a single scale i.e mean is 0 & SD is 1

### z-score standardization = (data_point1 - Column_mean) + (data_point1 - Column_mean) +....+ (data_point1 - Column_mean)          
###                           -------------------------------------------------------------------------------------------
###                                                           Standard_deviation
### Standard_deviation = Square root of Variance

### Variance = ((data_point1 - Column_mean)**2) + ((data_point2 - Column_mean)**2) +...+ ((data_point_n - Column_mean)**2)
###            -----------------------------------------------------------------------------------------------------------
###                                               len(column)

In [41]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [42]:
x_train[:5]

array([[-1.15687814e+00, -8.96200501e-01, -1.00392807e+00,
        -1.25782829e+00, -1.14563966e+00, -1.20379368e+00,
        -6.14216360e-01, -9.48610283e-01],
       [ 2.28370750e-01, -5.64089421e-01, -1.97904130e-02,
         4.16397301e-02,  1.99702256e+00,  6.64529988e-01,
        -9.09737865e-01, -4.34666726e-01],
       [ 6.15174086e-16,  4.32243819e-01, -3.47836300e-01,
         1.57737467e+00,  1.11425228e+00,  1.44060290e+00,
        -3.06991033e-01, -7.77295764e-01],
       [-1.17941473e-01,  2.99399387e-01, -3.47836300e-01,
        -9.03427923e-01,  1.25549552e-01,  1.18404607e-01,
        -9.06811910e-01, -4.34666726e-01],
       [-1.15687814e+00, -6.30511637e-01, -3.46427222e+00,
         1.10484084e+00, -8.51382901e-01,  1.58432010e+00,
        -8.39514933e-01, -6.38042901e-03]])

# Training the 3 different models

In [43]:
# Traning the Naive Bayes model

nb_model = GaussianNB()
nb_model.fit(x_train,y_train.ravel())

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)number of training samples observed in each class.","ndarray[float64](2,)","[349.,188.]"
"class_prior_ class_prior_: ndarray of shape (n_classes,)probability of each class.","ndarray[float64](2,)","[0.65,0.35]"
"classes_ classes_: ndarray of shape (n_classes,)class labels known to the classifier.","ndarray[int64](2,)","[0,1]"
epsilon_ epsilon_: floatabsolute additive value to variances.,float64,1e-09
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,8
"theta_ theta_: ndarray of shape (n_classes, n_features)mean of each feature per class.","ndarray[float64](2, 8)","[[-0.16,-0.38,-0.13,...,-0.25,-0.11,-0.21], [ 0.31, 0.7 , 0.24,..., 0.46, 0.2 , 0.38]]"
"var_ var_: ndarray of shape (n_classes, n_features)Variance of each feature per class... versionadded:: 1.0","ndarray[float64](2, 8)","[[0.86,0.61,0.97,...,0.87,0.84,0.94], [1.12,0.96,0.98,...,0.92,1.24,0.89]]"


In [44]:
# Traning the Random Forest model

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(x_train,y_train.ravel())

,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

In [45]:
# Traning the KNN model

knn_model = KNeighborsClassifier()
knn_model.fit(x_train,y_train.ravel())

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",None
Name,Type,Value
"classes_ classes_: array of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"effective_metric_ effective_metric_: str or callbleThe distance metric used. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'


# Testing on Train Data 

In [46]:
# Testing the Naive Bayes model using train data
nb_predict_train = nb_model.predict(x_train)

# checking Naive Bayes Model Accuracy on train data
print(f"predicted accuracy of navis bayees model is {metrics.accuracy_score(y_train,nb_predict_train )*100}")

predicted accuracy of navis bayees model is 75.41899441340783


In [47]:
# Testing the Random Forest model using train data
rf_pred_train = rf_model.predict(x_train)

# checking Random Forest Model Accuracy on train data
print(f"predicted accuracy of random forest model is {metrics.accuracy_score(y_train,rf_pred_train )*100}")

predicted accuracy of random forest model is 100.0


In [48]:
# Testing the KNN model using train data
knn_pred_train = knn_model.predict(x_train)

# checking KNN Model Accuracy on train data
print(f"predicted accuracy of KNN model is {metrics.accuracy_score(y_train,knn_pred_train )*100}")

predicted accuracy of KNN model is 83.79888268156425


# Testing on Test Data

In [49]:
# Testing the Naive Bayes model using test data
nb_predict_test = nb_model.predict(x_test)

# checking Naive Bayes Model Accuracy on test data
print(f"predicted accuracy of navis bayees model is {metrics.accuracy_score(y_test,nb_predict_test )*100}")

predicted accuracy of navis bayees model is 73.59307359307358


In [50]:
# Testing the Random Forest model using test data
rf_pred_test = rf_model.predict(x_test)

# checking Random Forest model Accuracy on test data
print(f"predicted accuracy of random forest model is {metrics.accuracy_score(y_test,rf_pred_test )*100}")

predicted accuracy of random forest model is 74.45887445887446


In [51]:
# Testing the KNN model using test data
knn_pred_test = knn_model.predict(x_test)

# checking KNN Model Accuracy on test data
print(f"predicted accuracy of KNN model is {metrics.accuracy_score(y_test,knn_pred_test )*100}")

predicted accuracy of KNN model is 70.12987012987013


In [52]:
## Evaluating by Confusion Matrix and Classification report

# Using Confusion Matrix

In [53]:
# confusion metrics for Naive Bayes Model
print(f'{metrics.confusion_matrix(y_test, nb_predict_test)} confusion metrics of Naive Bayes Model')


[[118  33]
 [ 28  52]] confusion metrics of Naive Bayes Model


In [54]:
((118+52)/(118+33+28+52))*100

73.59307359307358

In [55]:
# confusion metrics for Random Forest Model
print(f'{metrics.confusion_matrix(y_test, rf_pred_test)} confusion metrics of Random Forest Model')

[[120  31]
 [ 28  52]] confusion metrics of Random Forest Model


In [56]:
((120+52)/(120+31+28+52))*100

74.45887445887446

In [57]:
# confusion metrics for KNN Model
print(f'{metrics.confusion_matrix(y_test,knn_pred_test )} confusion metrics of KNN Model')

[[113  38]
 [ 31  49]] confusion metrics of KNN Model


In [58]:
((113+49)/(113+38+31+49))*100

70.12987012987013

# Using Classification Report

In [59]:
# Classification report for Naive Bayes Model
print(f'Classification report of Naive Bayes Model \n {metrics.classification_report(y_test, nb_predict_test)} ')

Classification report of Naive Bayes Model 
               precision    recall  f1-score   support

           0       0.81      0.78      0.79       151
           1       0.61      0.65      0.63        80

    accuracy                           0.74       231
   macro avg       0.71      0.72      0.71       231
weighted avg       0.74      0.74      0.74       231
 


In [60]:
# Classification report for Random Forest Model
print(f'Classification report of Random Forest Model \n {metrics.classification_report(y_test, rf_pred_test)} ')

Classification report of Random Forest Model 
               precision    recall  f1-score   support

           0       0.81      0.79      0.80       151
           1       0.63      0.65      0.64        80

    accuracy                           0.74       231
   macro avg       0.72      0.72      0.72       231
weighted avg       0.75      0.74      0.75       231
 


In [61]:
# Classification report for KNN Model
print(f'Classification report of KNN Model \n {metrics.classification_report(y_test, knn_pred_test)} ')

Classification report of KNN Model 
               precision    recall  f1-score   support

           0       0.78      0.75      0.77       151
           1       0.56      0.61      0.59        80

    accuracy                           0.70       231
   macro avg       0.67      0.68      0.68       231
weighted avg       0.71      0.70      0.70       231
 


## Conclusion: Random Forest is the best suitable model