## numpy stands numerical python.
## It is used to do high level mathematical and stastical calculations.

In [1]:
import numpy as np
## import is a keyword which is used to import all dependenices.
## as is a keyword to provide alias name for your libraries.

# list -- it is advanced datatype which is used to store list of elements.
## it is denoted by squre brackets
## each elements is seperated by comma
## it allows both homogeneous and hetrogeneous elements
## list is mutable and tuple is immutable
## Indexing are two type +ve(0 to x-1) and -ve

In [2]:
a1 = [10,40,30,92]
print(a1)
print(len(a1))
print(a1[0])
print(a1[-2])
print(a1[-1])

a1[3]=50
print(a1)

[10, 40, 30, 92]
4
10
30
92
[10, 40, 30, 50]


In [3]:
lis1 = [10,20,30,40,50]
print(lis1)

[10, 20, 30, 40, 50]


In [4]:
x = list(range(10))
print (x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
print(type(x))

<class 'list'>


In [6]:
tup = (1,2,3,5)
print (tup)

(1, 2, 3, 5)


In [7]:
y = tuple (range(1,5))
print(y)

(1, 2, 3, 4)


In [8]:
print(type(y))

<class 'tuple'>


In [9]:
x1 = [10,20+8j,True,"Palle"]
print(type(x1))

<class 'list'>


# Creating numpy arrays

## Creating arrays using list

In [10]:
lis1 = [10,20,30,40]
arr1 = np.array(lis1)
print(arr1)

[10 20 30 40]


## Creating arrays using tuple

In [11]:
tuple1 = (10,20,30,50)
arr2 = np.array(tuple1)
print(arr2)
print(type(arr2))

[10 20 30 50]
<class 'numpy.ndarray'>


## Creating a numpy arrays using list and store float value

In [12]:
list2 = [20,50,90,10]
arr3 = np.array(list2,dtype=float)
print(arr3)
print(type(arr3))

[20. 50. 90. 10.]
<class 'numpy.ndarray'>


In [13]:
list2 = [20,50,90,10]
arr3 = np.array(list2,dtype=bool)
print(arr3)

[ True  True  True  True]


# Oder of datatype

## Arrays allows only homogeneous
## str,complex,float,int,bool

In [14]:
list4 = [10,50.2,20+8j,True,"Palle"]
arr4 = np.array(list4)
print(arr4)

['10' '50.2' '(20+8j)' 'True' 'Palle']


In [15]:
list4 = [10,50.2,20+8j,True]
arr4 = np.array(list4)
print(arr4)

[10. +0.j 50.2+0.j 20. +8.j  1. +0.j]


In [16]:
list4 = [10,50.2,True]
arr4 = np.array(list4)
print(arr4)

[10.  50.2  1. ]


In [17]:
list4 = [10,True]
arr4 = np.array(list4)
print(arr4)

[10  1]


In [18]:
d1= {(12,25,59,54):"tuple1"}
print(d1)

{(12, 25, 59, 54): 'tuple1'}


In [19]:
## d2= {"10":"ten",[12,25,59,54]:"tuple1"}
## print(d2)

## set is mutable and in set elements are immutable 

In [20]:
set1 = {14,29,49}
set1.add(59)
print(set1)

{49, 59, 29, 14}


In [21]:
## set2 = {14,29,49,[1,2,3]}
## print(set2)

In [22]:
print(dir(set1))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


# Generating the elements

In [23]:
r1 = list(range(1,10,2))
print(r1)

[1, 3, 5, 7, 9]


In [24]:
## r1 = list(range(1,10,0.5))
## print(r1)

In [25]:
arr5 = np.arange(1,10,0.5)
print(arr5)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [26]:
arr6 = np.linspace(1,10,10)
print(arr6)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [27]:
arr6 = np.linspace(1,10,4)
print(arr6)

[ 1.  4.  7. 10.]


In [28]:
arr7 = np.linspace(1,10,10,dtype=int)
print(arr7)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
arr8 = np.arange(1,10,0.5,dtype=int)
print(arr8)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [30]:
print(int(0.5))

0


In [31]:
print(int(1.5))

1


# Creating 2d array using nested list

In [32]:
list6 = [[10,20,30,40],[50,60,70,80]]
arr6 = np.array(list6)
print(arr6)

[[10 20 30 40]
 [50 60 70 80]]


In [33]:
print(len(arr6))
print(arr6.ndim)
print(arr6.shape)
print(arr6.size)

2
2
(2, 4)
8


# Creating 2d array using arange and reshape

In [34]:
arr7 = np.arange(1,10).reshape(3,3)
print(arr7)
print(arr7.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [35]:
arr8 = np.arange(1,11).reshape(5,2)
print(arr8)
print(arr8.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2


# Flattened the array

In [36]:
list9 = [[1,2],[3,4],[5,6]]
arr9 = np.array(list9)
print(arr9.flatten())

[1 2 3 4 5 6]


In [37]:
print(10+5)
print([10]+[5])

15
[10, 5]


## Arithematic operations

In [38]:
z1 = np.arange(1,5).reshape(2,2)
z2 = np.arange(1,5).reshape(2,2)
print(z1)
print(z2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [39]:
print(z1+5)

[[6 7]
 [8 9]]


In [40]:
print(z1-5)

[[-4 -3]
 [-2 -1]]


In [41]:
print(z1*5)

[[ 5 10]
 [15 20]]


In [42]:
print(z1/5)

[[0.2 0.4]
 [0.6 0.8]]


In [43]:
print(z1//5)

[[0 0]
 [0 0]]


In [44]:
print(z1%5)

[[1 2]
 [3 4]]


In [45]:
print(z1 ** 5)

[[   1   32]
 [ 243 1024]]


In [46]:
z3 = np.arange(1,6)
print(z3)

[1 2 3 4 5]


In [47]:
print(np.repeat(z3,5))

[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5]


In [48]:
print(np.tile(z3,5))

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [49]:
## print([10,20,30,40] + 5)
## print([10,20,30,40] - 5)
print([10,20,30,40] * 5)
## print([10,20,30,40] // 5)

[10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]


# Acessing the elements from array

In [50]:
arr11 = np.arange(1,21).reshape(5,4)
print(arr11)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [51]:
print(arr11[0])

[1 2 3 4]


In [52]:
print(arr11[-1])

[17 18 19 20]


In [53]:
print(arr11[2])

[ 9 10 11 12]


In [54]:
print(arr11[0][0])

1


In [55]:
print(arr11[0][: :-1])

[4 3 2 1]


In [56]:
print(arr11[: : -1])

[[17 18 19 20]
 [13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [57]:
print(arr11[0:2,0:2])

[[1 2]
 [5 6]]


In [58]:
print(arr11[0:6,0:2])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]]


In [59]:
print(arr11[0:5,3])

[ 4  8 12 16 20]


In [60]:
print(arr11[0:5,-1:-2:-1])

[[ 4]
 [ 8]
 [12]
 [16]
 [20]]


In [61]:
print(arr11[: : -1,: : -1])

[[20 19 18 17]
 [16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


# Martices

In [62]:
b1 = np.arange(1,5).reshape(2,2)
b2 = np.arange(1,5).reshape(2,2)

In [63]:
b1

array([[1, 2],
       [3, 4]])

In [64]:
b2

array([[1, 2],
       [3, 4]])

In [65]:
b1*b2

array([[ 1,  4],
       [ 9, 16]])

In [66]:
np.dot(b1,b2)

array([[ 7, 10],
       [15, 22]])

In [67]:
a1 = np.arange(1,3).reshape(1,2)
a2 = np.arange(1,3).reshape(2,1)
print(a1)
print(a2)

[[1 2]]
[[1]
 [2]]


In [68]:
print(np.dot(a1,a2))

[[5]]


In [69]:
# Matrix Rule :- 
## No. of columns in 1st matrix and no. of rows in 2nd matrix need to same
## Built in fun'n to create matrix

In [70]:
n0 = np.zeros((3,3),dtype = int)
print(n0)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [71]:
n1 = np.ones((3,3),dtype = int)
print(n1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [72]:
n3 = np.full((3,3),3,dtype = int)
print(n3)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


# Aggregate funtions

In [80]:
agg1 = np.random.randint(1,50,15)
print(agg1)

[36 33  6 36 39 26 31  6  1 39 49 45  9 11 19]


In [81]:
print(np.min(agg1))
print(np.max(agg1))
print(np.argmin(agg1))
print(np.argmax(agg1))
print(np.mean(agg1))
print(np.median(agg1))

1
49
8
10
25.733333333333334
31.0


# Joins

In [82]:
arr31 = np.arange(1,10).reshape(3,3)
arr32 = np.arange(1,10).reshape(3,3)
print(arr31)
print(arr32)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
print(np.concatenate((arr31,arr32),axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
print(np.concatenate((arr31,arr32),axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
